version: 2.1

orbs:
  architect: giantswarm/architect@4.37.0

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-test
          filters:
            tags:
              only: /^v.*/
