version: 2.1

orbs:
  architect: giantswarm/architect@4.31.0

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/pr-comment-filter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-test
          filters:
            tags:
              only: /^v.*/
