version: 2.1

orbs:
  architect: giantswarm/architect@6.1.0

workflows:
  build:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          name: push-to-registries
          context: architect
          requires:
            - go-test
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/
